schema:
  - https://gateway.ui.dev-core.mcpd.shoot.canary.k8s-hana.ondemand.com/api/clusters/single-onboarding/graphql:
      headers:
        Authorization: ${GRAPHQL_AUTH_TOKEN}
documents: './src/**/*.{ts,tsx}'
ignoreNoDocuments: true
extensions:
  codegen:
    hooks:
      afterAllFileWrite:
        - prettier --write
    generates:
      ./src/types/__generated__/graphql/:
        preset: client
        presetConfig:
          gqlTagName: graphql
