/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  '\n  query GetCrossplane($name: String!, $namespace: String) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        Crossplane(name: $name, namespace: $namespace) {\n          kind\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n            providers {\n              name\n              version\n            }\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n': typeof types.GetCrossplaneDocument;
  '\n  query GetExternalSecretsOperator($name: String!, $namespace: String) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        ExternalSecretsOperator(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n': typeof types.GetExternalSecretsOperatorDocument;
  '\n  query GetFlux($name: String!, $namespace: String) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        Flux(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n': typeof types.GetFluxDocument;
  '\n  query GetLandscaper($name: String!, $namespace: String) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        Landscaper(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            phase\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n': typeof types.GetLandscaperDocument;
  '\n  mutation CreateCrossplane(\n    $namespace: String\n    $object: CrossplaneServicesOpenControlPlaneIoV1alpha1Crossplane_Input!\n  ) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        createCrossplane(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.CreateCrossplaneDocument;
  '\n  mutation CreateExternalSecretsOperator(\n    $namespace: String\n    $object: ExternalSecretsServicesOpenControlPlaneIoV1alpha1ExternalSecretsOperator_Input!\n  ) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        createExternalSecretsOperator(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.CreateExternalSecretsOperatorDocument;
  '\n  mutation CreateFlux($namespace: String, $object: FluxServicesOpenControlPlaneIoV1alpha1Flux_Input!) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        createFlux(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.CreateFluxDocument;
  '\n  mutation CreateLandscaper(\n    $namespace: String\n    $object: LandscaperServicesOpenControlPlaneIoV1alpha2Landscaper_Input!\n  ) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        createLandscaper(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.CreateLandscaperDocument;
  '\n  mutation CreateManagedControlPlaneV2(\n    $namespace: String\n    $object: CoreOpenControlPlaneIoV2alpha1ControlPlane_Input!\n    $dryRun: Boolean\n  ) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        createControlPlane(namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n          status {\n            phase\n          }\n        }\n      }\n    }\n  }\n': typeof types.CreateManagedControlPlaneV2Document;
  '\n  mutation DeleteCrossplane($name: String!, $namespace: String) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        deleteCrossplane(name: $name, namespace: $namespace)\n      }\n    }\n  }\n': typeof types.DeleteCrossplaneDocument;
  '\n  mutation DeleteExternalSecretsOperator($name: String!, $namespace: String) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        deleteExternalSecretsOperator(name: $name, namespace: $namespace)\n      }\n    }\n  }\n': typeof types.DeleteExternalSecretsOperatorDocument;
  '\n  mutation DeleteFlux($name: String!, $namespace: String) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        deleteFlux(name: $name, namespace: $namespace)\n      }\n    }\n  }\n': typeof types.DeleteFluxDocument;
  '\n  mutation DeleteLandscaper($name: String!, $namespace: String) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        deleteLandscaper(name: $name, namespace: $namespace)\n      }\n    }\n  }\n': typeof types.DeleteLandscaperDocument;
  '\n  mutation DeleteManagedControlPlaneV2($name: String!, $namespace: String, $dryRun: Boolean) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        deleteControlPlane(name: $name, namespace: $namespace, dryRun: $dryRun)\n      }\n    }\n  }\n': typeof types.DeleteManagedControlPlaneV2Document;
  '\n  mutation UpdateCrossplane(\n    $namespace: String\n    $name: String!\n    $object: CrossplaneServicesOpenControlPlaneIoV1alpha1Crossplane_Input!\n  ) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        updateCrossplane(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.UpdateCrossplaneDocument;
  '\n  mutation UpdateExternalSecretsOperator(\n    $namespace: String\n    $name: String!\n    $object: ExternalSecretsServicesOpenControlPlaneIoV1alpha1ExternalSecretsOperator_Input!\n  ) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        updateExternalSecretsOperator(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.UpdateExternalSecretsOperatorDocument;
  '\n  mutation UpdateFlux($namespace: String, $name: String!, $object: FluxServicesOpenControlPlaneIoV1alpha1Flux_Input!) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        updateFlux(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.UpdateFluxDocument;
  '\n  mutation UpdateLandscaper(\n    $namespace: String\n    $name: String!\n    $object: LandscaperServicesOpenControlPlaneIoV1alpha2Landscaper_Input!\n  ) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        updateLandscaper(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.UpdateLandscaperDocument;
  '\n  mutation UpdateManagedControlPlaneV2(\n    $name: String!\n    $namespace: String\n    $object: CoreOpenControlPlaneIoV2alpha1ControlPlane_Input!\n    $dryRun: Boolean\n  ) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        updateControlPlane(name: $name, namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n          status {\n            phase\n          }\n        }\n      }\n    }\n  }\n': typeof types.UpdateManagedControlPlaneV2Document;
  '\n  mutation CreateProject($object: CoreOpenmcpCloudV1alpha1Project_Input!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        createProject(object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n          }\n        }\n      }\n    }\n  }\n': typeof types.CreateProjectDocument;
  '\n  mutation CreateWorkspace($namespace: String!, $object: CoreOpenmcpCloudV1alpha1Workspace_Input!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        createWorkspace(namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n': typeof types.CreateWorkspaceDocument;
  '\n  mutation DeleteProject($name: String!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        deleteProject(name: $name, dryRun: $dryRun)\n      }\n    }\n  }\n': typeof types.DeleteProjectDocument;
  '\n  mutation DeleteWorkspace($name: String!, $namespace: String, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        deleteWorkspace(name: $name, namespace: $namespace, dryRun: $dryRun)\n      }\n    }\n  }\n': typeof types.DeleteWorkspaceDocument;
  '\n  query GetKubeconfig($kubeConfigName: String!, $namespaceName: String) {\n    v1 {\n      Secret(name: $kubeConfigName, namespace: $namespaceName) {\n        data\n      }\n    }\n  }\n': typeof types.GetKubeconfigDocument;
  '\n  query GetMCPv2($name: String!, $namespace: String) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        ControlPlane(name: $name, namespace: $namespace) {\n          kind\n          metadata {\n            name\n            namespace\n            annotations\n            creationTimestamp\n          }\n          spec {\n            iam {\n              oidc {\n                defaultProvider {\n                  roleBindings {\n                    roleRefs {\n                      kind\n                      name\n                      namespace\n                    }\n                    subjects {\n                      apiGroup\n                      kind\n                      name\n                      namespace\n                    }\n                  }\n                }\n                extraProviders {\n                  roleBindings {\n                    roleRefs {\n                      kind\n                      name\n                      namespace\n                    }\n                    subjects {\n                      apiGroup\n                      kind\n                      name\n                      namespace\n                    }\n                  }\n                }\n              }\n              tokens {\n                name\n                permissions {\n                  rules {\n                    apiGroups\n                    resources\n                    verbs\n                  }\n                }\n                roleRefs {\n                  kind\n                  name\n                  namespace\n                }\n              }\n            }\n          }\n          status {\n            phase\n            access\n            observedGeneration\n            conditions {\n              type\n              status\n              reason\n              message\n              lastTransitionTime\n            }\n          }\n        }\n      }\n    }\n  }\n': typeof types.GetMcPv2Document;
  '\n  query GetMCPsList($workspaceNamespace: String!) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        ManagedControlPlanes(namespace: $workspaceNamespace) {\n          items {\n            metadata {\n              name\n              namespace\n              creationTimestamp\n              annotations\n            }\n            status {\n              status\n              conditions {\n                type\n                status\n                reason\n                message\n                lastTransitionTime\n              }\n              components {\n                authentication {\n                  access {\n                    key\n                    name\n                    namespace\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    core_open_control_plane_io {\n      v2alpha1 {\n        ControlPlanes(namespace: $workspaceNamespace) {\n          items {\n            metadata {\n              name\n              namespace\n              creationTimestamp\n              annotations\n            }\n            status {\n              phase\n              conditions {\n                type\n                status\n                reason\n                message\n                lastTransitionTime\n              }\n              access\n            }\n          }\n        }\n      }\n    }\n  }\n': typeof types.GetMcPsListDocument;
  '\n  mutation CreateSelfSubjectRulesReview($object: AuthorizationK8sIoV1SelfSubjectRulesReview_Input!) {\n    authorization_k8s_io {\n      v1 {\n        createSelfSubjectRulesReview(object: $object) {\n          status {\n            evaluationError\n            incomplete\n            resourceRules {\n              apiGroups\n              resources\n              verbs\n              resourceNames\n            }\n          }\n        }\n      }\n    }\n  }\n': typeof types.CreateSelfSubjectRulesReviewDocument;
  '\n  query GetWorkspaces($projectNamespace: String!) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        Workspaces(namespace: $projectNamespace) {\n          items {\n            apiVersion\n            kind\n            metadata {\n              name\n              namespace\n              annotations\n            }\n            spec {\n              members {\n                kind\n                name\n                roles\n                namespace\n              }\n            }\n            status {\n              namespace\n            }\n          }\n        }\n      }\n    }\n  }\n': typeof types.GetWorkspacesDocument;
  '\n  subscription WorkspacesSubscription($namespace: String!) {\n    core_openmcp_cloud_v1alpha1_workspaces(namespace: $namespace) {\n      type\n    }\n  }\n': typeof types.WorkspacesSubscriptionDocument;
};
const documents: Documents = {
  '\n  query GetCrossplane($name: String!, $namespace: String) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        Crossplane(name: $name, namespace: $namespace) {\n          kind\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n            providers {\n              name\n              version\n            }\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.GetCrossplaneDocument,
  '\n  query GetExternalSecretsOperator($name: String!, $namespace: String) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        ExternalSecretsOperator(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.GetExternalSecretsOperatorDocument,
  '\n  query GetFlux($name: String!, $namespace: String) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        Flux(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.GetFluxDocument,
  '\n  query GetLandscaper($name: String!, $namespace: String) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        Landscaper(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            phase\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.GetLandscaperDocument,
  '\n  mutation CreateCrossplane(\n    $namespace: String\n    $object: CrossplaneServicesOpenControlPlaneIoV1alpha1Crossplane_Input!\n  ) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        createCrossplane(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.CreateCrossplaneDocument,
  '\n  mutation CreateExternalSecretsOperator(\n    $namespace: String\n    $object: ExternalSecretsServicesOpenControlPlaneIoV1alpha1ExternalSecretsOperator_Input!\n  ) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        createExternalSecretsOperator(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.CreateExternalSecretsOperatorDocument,
  '\n  mutation CreateFlux($namespace: String, $object: FluxServicesOpenControlPlaneIoV1alpha1Flux_Input!) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        createFlux(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.CreateFluxDocument,
  '\n  mutation CreateLandscaper(\n    $namespace: String\n    $object: LandscaperServicesOpenControlPlaneIoV1alpha2Landscaper_Input!\n  ) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        createLandscaper(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.CreateLandscaperDocument,
  '\n  mutation CreateManagedControlPlaneV2(\n    $namespace: String\n    $object: CoreOpenControlPlaneIoV2alpha1ControlPlane_Input!\n    $dryRun: Boolean\n  ) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        createControlPlane(namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n          status {\n            phase\n          }\n        }\n      }\n    }\n  }\n':
    types.CreateManagedControlPlaneV2Document,
  '\n  mutation DeleteCrossplane($name: String!, $namespace: String) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        deleteCrossplane(name: $name, namespace: $namespace)\n      }\n    }\n  }\n':
    types.DeleteCrossplaneDocument,
  '\n  mutation DeleteExternalSecretsOperator($name: String!, $namespace: String) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        deleteExternalSecretsOperator(name: $name, namespace: $namespace)\n      }\n    }\n  }\n':
    types.DeleteExternalSecretsOperatorDocument,
  '\n  mutation DeleteFlux($name: String!, $namespace: String) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        deleteFlux(name: $name, namespace: $namespace)\n      }\n    }\n  }\n':
    types.DeleteFluxDocument,
  '\n  mutation DeleteLandscaper($name: String!, $namespace: String) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        deleteLandscaper(name: $name, namespace: $namespace)\n      }\n    }\n  }\n':
    types.DeleteLandscaperDocument,
  '\n  mutation DeleteManagedControlPlaneV2($name: String!, $namespace: String, $dryRun: Boolean) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        deleteControlPlane(name: $name, namespace: $namespace, dryRun: $dryRun)\n      }\n    }\n  }\n':
    types.DeleteManagedControlPlaneV2Document,
  '\n  mutation UpdateCrossplane(\n    $namespace: String\n    $name: String!\n    $object: CrossplaneServicesOpenControlPlaneIoV1alpha1Crossplane_Input!\n  ) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        updateCrossplane(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.UpdateCrossplaneDocument,
  '\n  mutation UpdateExternalSecretsOperator(\n    $namespace: String\n    $name: String!\n    $object: ExternalSecretsServicesOpenControlPlaneIoV1alpha1ExternalSecretsOperator_Input!\n  ) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        updateExternalSecretsOperator(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.UpdateExternalSecretsOperatorDocument,
  '\n  mutation UpdateFlux($namespace: String, $name: String!, $object: FluxServicesOpenControlPlaneIoV1alpha1Flux_Input!) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        updateFlux(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.UpdateFluxDocument,
  '\n  mutation UpdateLandscaper(\n    $namespace: String\n    $name: String!\n    $object: LandscaperServicesOpenControlPlaneIoV1alpha2Landscaper_Input!\n  ) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        updateLandscaper(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.UpdateLandscaperDocument,
  '\n  mutation UpdateManagedControlPlaneV2(\n    $name: String!\n    $namespace: String\n    $object: CoreOpenControlPlaneIoV2alpha1ControlPlane_Input!\n    $dryRun: Boolean\n  ) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        updateControlPlane(name: $name, namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n          status {\n            phase\n          }\n        }\n      }\n    }\n  }\n':
    types.UpdateManagedControlPlaneV2Document,
  '\n  mutation CreateProject($object: CoreOpenmcpCloudV1alpha1Project_Input!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        createProject(object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n          }\n        }\n      }\n    }\n  }\n':
    types.CreateProjectDocument,
  '\n  mutation CreateWorkspace($namespace: String!, $object: CoreOpenmcpCloudV1alpha1Workspace_Input!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        createWorkspace(namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n':
    types.CreateWorkspaceDocument,
  '\n  mutation DeleteProject($name: String!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        deleteProject(name: $name, dryRun: $dryRun)\n      }\n    }\n  }\n':
    types.DeleteProjectDocument,
  '\n  mutation DeleteWorkspace($name: String!, $namespace: String, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        deleteWorkspace(name: $name, namespace: $namespace, dryRun: $dryRun)\n      }\n    }\n  }\n':
    types.DeleteWorkspaceDocument,
  '\n  query GetKubeconfig($kubeConfigName: String!, $namespaceName: String) {\n    v1 {\n      Secret(name: $kubeConfigName, namespace: $namespaceName) {\n        data\n      }\n    }\n  }\n':
    types.GetKubeconfigDocument,
  '\n  query GetMCPv2($name: String!, $namespace: String) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        ControlPlane(name: $name, namespace: $namespace) {\n          kind\n          metadata {\n            name\n            namespace\n            annotations\n            creationTimestamp\n          }\n          spec {\n            iam {\n              oidc {\n                defaultProvider {\n                  roleBindings {\n                    roleRefs {\n                      kind\n                      name\n                      namespace\n                    }\n                    subjects {\n                      apiGroup\n                      kind\n                      name\n                      namespace\n                    }\n                  }\n                }\n                extraProviders {\n                  roleBindings {\n                    roleRefs {\n                      kind\n                      name\n                      namespace\n                    }\n                    subjects {\n                      apiGroup\n                      kind\n                      name\n                      namespace\n                    }\n                  }\n                }\n              }\n              tokens {\n                name\n                permissions {\n                  rules {\n                    apiGroups\n                    resources\n                    verbs\n                  }\n                }\n                roleRefs {\n                  kind\n                  name\n                  namespace\n                }\n              }\n            }\n          }\n          status {\n            phase\n            access\n            observedGeneration\n            conditions {\n              type\n              status\n              reason\n              message\n              lastTransitionTime\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.GetMcPv2Document,
  '\n  query GetMCPsList($workspaceNamespace: String!) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        ManagedControlPlanes(namespace: $workspaceNamespace) {\n          items {\n            metadata {\n              name\n              namespace\n              creationTimestamp\n              annotations\n            }\n            status {\n              status\n              conditions {\n                type\n                status\n                reason\n                message\n                lastTransitionTime\n              }\n              components {\n                authentication {\n                  access {\n                    key\n                    name\n                    namespace\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    core_open_control_plane_io {\n      v2alpha1 {\n        ControlPlanes(namespace: $workspaceNamespace) {\n          items {\n            metadata {\n              name\n              namespace\n              creationTimestamp\n              annotations\n            }\n            status {\n              phase\n              conditions {\n                type\n                status\n                reason\n                message\n                lastTransitionTime\n              }\n              access\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.GetMcPsListDocument,
  '\n  mutation CreateSelfSubjectRulesReview($object: AuthorizationK8sIoV1SelfSubjectRulesReview_Input!) {\n    authorization_k8s_io {\n      v1 {\n        createSelfSubjectRulesReview(object: $object) {\n          status {\n            evaluationError\n            incomplete\n            resourceRules {\n              apiGroups\n              resources\n              verbs\n              resourceNames\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.CreateSelfSubjectRulesReviewDocument,
  '\n  query GetWorkspaces($projectNamespace: String!) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        Workspaces(namespace: $projectNamespace) {\n          items {\n            apiVersion\n            kind\n            metadata {\n              name\n              namespace\n              annotations\n            }\n            spec {\n              members {\n                kind\n                name\n                roles\n                namespace\n              }\n            }\n            status {\n              namespace\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.GetWorkspacesDocument,
  '\n  subscription WorkspacesSubscription($namespace: String!) {\n    core_openmcp_cloud_v1alpha1_workspaces(namespace: $namespace) {\n      type\n    }\n  }\n':
    types.WorkspacesSubscriptionDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetCrossplane($name: String!, $namespace: String) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        Crossplane(name: $name, namespace: $namespace) {\n          kind\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n            providers {\n              name\n              version\n            }\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetCrossplane($name: String!, $namespace: String) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        Crossplane(name: $name, namespace: $namespace) {\n          kind\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n            providers {\n              name\n              version\n            }\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetExternalSecretsOperator($name: String!, $namespace: String) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        ExternalSecretsOperator(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetExternalSecretsOperator($name: String!, $namespace: String) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        ExternalSecretsOperator(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetFlux($name: String!, $namespace: String) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        Flux(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetFlux($name: String!, $namespace: String) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        Flux(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetLandscaper($name: String!, $namespace: String) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        Landscaper(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            phase\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetLandscaper($name: String!, $namespace: String) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        Landscaper(name: $name, namespace: $namespace) {\n          metadata {\n            name\n            namespace\n          }\n          spec {\n            version\n          }\n          status {\n            phase\n            conditions {\n              type\n              status\n              reason\n              message\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation CreateCrossplane(\n    $namespace: String\n    $object: CrossplaneServicesOpenControlPlaneIoV1alpha1Crossplane_Input!\n  ) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        createCrossplane(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation CreateCrossplane(\n    $namespace: String\n    $object: CrossplaneServicesOpenControlPlaneIoV1alpha1Crossplane_Input!\n  ) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        createCrossplane(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation CreateExternalSecretsOperator(\n    $namespace: String\n    $object: ExternalSecretsServicesOpenControlPlaneIoV1alpha1ExternalSecretsOperator_Input!\n  ) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        createExternalSecretsOperator(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation CreateExternalSecretsOperator(\n    $namespace: String\n    $object: ExternalSecretsServicesOpenControlPlaneIoV1alpha1ExternalSecretsOperator_Input!\n  ) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        createExternalSecretsOperator(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation CreateFlux($namespace: String, $object: FluxServicesOpenControlPlaneIoV1alpha1Flux_Input!) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        createFlux(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation CreateFlux($namespace: String, $object: FluxServicesOpenControlPlaneIoV1alpha1Flux_Input!) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        createFlux(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation CreateLandscaper(\n    $namespace: String\n    $object: LandscaperServicesOpenControlPlaneIoV1alpha2Landscaper_Input!\n  ) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        createLandscaper(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation CreateLandscaper(\n    $namespace: String\n    $object: LandscaperServicesOpenControlPlaneIoV1alpha2Landscaper_Input!\n  ) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        createLandscaper(namespace: $namespace, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation CreateManagedControlPlaneV2(\n    $namespace: String\n    $object: CoreOpenControlPlaneIoV2alpha1ControlPlane_Input!\n    $dryRun: Boolean\n  ) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        createControlPlane(namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n          status {\n            phase\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation CreateManagedControlPlaneV2(\n    $namespace: String\n    $object: CoreOpenControlPlaneIoV2alpha1ControlPlane_Input!\n    $dryRun: Boolean\n  ) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        createControlPlane(namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n          status {\n            phase\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation DeleteCrossplane($name: String!, $namespace: String) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        deleteCrossplane(name: $name, namespace: $namespace)\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation DeleteCrossplane($name: String!, $namespace: String) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        deleteCrossplane(name: $name, namespace: $namespace)\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation DeleteExternalSecretsOperator($name: String!, $namespace: String) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        deleteExternalSecretsOperator(name: $name, namespace: $namespace)\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation DeleteExternalSecretsOperator($name: String!, $namespace: String) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        deleteExternalSecretsOperator(name: $name, namespace: $namespace)\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation DeleteFlux($name: String!, $namespace: String) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        deleteFlux(name: $name, namespace: $namespace)\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation DeleteFlux($name: String!, $namespace: String) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        deleteFlux(name: $name, namespace: $namespace)\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation DeleteLandscaper($name: String!, $namespace: String) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        deleteLandscaper(name: $name, namespace: $namespace)\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation DeleteLandscaper($name: String!, $namespace: String) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        deleteLandscaper(name: $name, namespace: $namespace)\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation DeleteManagedControlPlaneV2($name: String!, $namespace: String, $dryRun: Boolean) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        deleteControlPlane(name: $name, namespace: $namespace, dryRun: $dryRun)\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation DeleteManagedControlPlaneV2($name: String!, $namespace: String, $dryRun: Boolean) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        deleteControlPlane(name: $name, namespace: $namespace, dryRun: $dryRun)\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation UpdateCrossplane(\n    $namespace: String\n    $name: String!\n    $object: CrossplaneServicesOpenControlPlaneIoV1alpha1Crossplane_Input!\n  ) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        updateCrossplane(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation UpdateCrossplane(\n    $namespace: String\n    $name: String!\n    $object: CrossplaneServicesOpenControlPlaneIoV1alpha1Crossplane_Input!\n  ) {\n    crossplane_services_open_control_plane_io {\n      v1alpha1 {\n        updateCrossplane(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation UpdateExternalSecretsOperator(\n    $namespace: String\n    $name: String!\n    $object: ExternalSecretsServicesOpenControlPlaneIoV1alpha1ExternalSecretsOperator_Input!\n  ) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        updateExternalSecretsOperator(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation UpdateExternalSecretsOperator(\n    $namespace: String\n    $name: String!\n    $object: ExternalSecretsServicesOpenControlPlaneIoV1alpha1ExternalSecretsOperator_Input!\n  ) {\n    external_secrets_services_open_control_plane_io {\n      v1alpha1 {\n        updateExternalSecretsOperator(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation UpdateFlux($namespace: String, $name: String!, $object: FluxServicesOpenControlPlaneIoV1alpha1Flux_Input!) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        updateFlux(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation UpdateFlux($namespace: String, $name: String!, $object: FluxServicesOpenControlPlaneIoV1alpha1Flux_Input!) {\n    flux_services_open_control_plane_io {\n      v1alpha1 {\n        updateFlux(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation UpdateLandscaper(\n    $namespace: String\n    $name: String!\n    $object: LandscaperServicesOpenControlPlaneIoV1alpha2Landscaper_Input!\n  ) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        updateLandscaper(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation UpdateLandscaper(\n    $namespace: String\n    $name: String!\n    $object: LandscaperServicesOpenControlPlaneIoV1alpha2Landscaper_Input!\n  ) {\n    landscaper_services_open_control_plane_io {\n      v1alpha2 {\n        updateLandscaper(namespace: $namespace, name: $name, object: $object) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation UpdateManagedControlPlaneV2(\n    $name: String!\n    $namespace: String\n    $object: CoreOpenControlPlaneIoV2alpha1ControlPlane_Input!\n    $dryRun: Boolean\n  ) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        updateControlPlane(name: $name, namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n          status {\n            phase\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation UpdateManagedControlPlaneV2(\n    $name: String!\n    $namespace: String\n    $object: CoreOpenControlPlaneIoV2alpha1ControlPlane_Input!\n    $dryRun: Boolean\n  ) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        updateControlPlane(name: $name, namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n          status {\n            phase\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation CreateProject($object: CoreOpenmcpCloudV1alpha1Project_Input!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        createProject(object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation CreateProject($object: CoreOpenmcpCloudV1alpha1Project_Input!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        createProject(object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation CreateWorkspace($namespace: String!, $object: CoreOpenmcpCloudV1alpha1Workspace_Input!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        createWorkspace(namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation CreateWorkspace($namespace: String!, $object: CoreOpenmcpCloudV1alpha1Workspace_Input!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        createWorkspace(namespace: $namespace, object: $object, dryRun: $dryRun) {\n          metadata {\n            name\n            namespace\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation DeleteProject($name: String!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        deleteProject(name: $name, dryRun: $dryRun)\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation DeleteProject($name: String!, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        deleteProject(name: $name, dryRun: $dryRun)\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation DeleteWorkspace($name: String!, $namespace: String, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        deleteWorkspace(name: $name, namespace: $namespace, dryRun: $dryRun)\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation DeleteWorkspace($name: String!, $namespace: String, $dryRun: Boolean) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        deleteWorkspace(name: $name, namespace: $namespace, dryRun: $dryRun)\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetKubeconfig($kubeConfigName: String!, $namespaceName: String) {\n    v1 {\n      Secret(name: $kubeConfigName, namespace: $namespaceName) {\n        data\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetKubeconfig($kubeConfigName: String!, $namespaceName: String) {\n    v1 {\n      Secret(name: $kubeConfigName, namespace: $namespaceName) {\n        data\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetMCPv2($name: String!, $namespace: String) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        ControlPlane(name: $name, namespace: $namespace) {\n          kind\n          metadata {\n            name\n            namespace\n            annotations\n            creationTimestamp\n          }\n          spec {\n            iam {\n              oidc {\n                defaultProvider {\n                  roleBindings {\n                    roleRefs {\n                      kind\n                      name\n                      namespace\n                    }\n                    subjects {\n                      apiGroup\n                      kind\n                      name\n                      namespace\n                    }\n                  }\n                }\n                extraProviders {\n                  roleBindings {\n                    roleRefs {\n                      kind\n                      name\n                      namespace\n                    }\n                    subjects {\n                      apiGroup\n                      kind\n                      name\n                      namespace\n                    }\n                  }\n                }\n              }\n              tokens {\n                name\n                permissions {\n                  rules {\n                    apiGroups\n                    resources\n                    verbs\n                  }\n                }\n                roleRefs {\n                  kind\n                  name\n                  namespace\n                }\n              }\n            }\n          }\n          status {\n            phase\n            access\n            observedGeneration\n            conditions {\n              type\n              status\n              reason\n              message\n              lastTransitionTime\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetMCPv2($name: String!, $namespace: String) {\n    core_open_control_plane_io {\n      v2alpha1 {\n        ControlPlane(name: $name, namespace: $namespace) {\n          kind\n          metadata {\n            name\n            namespace\n            annotations\n            creationTimestamp\n          }\n          spec {\n            iam {\n              oidc {\n                defaultProvider {\n                  roleBindings {\n                    roleRefs {\n                      kind\n                      name\n                      namespace\n                    }\n                    subjects {\n                      apiGroup\n                      kind\n                      name\n                      namespace\n                    }\n                  }\n                }\n                extraProviders {\n                  roleBindings {\n                    roleRefs {\n                      kind\n                      name\n                      namespace\n                    }\n                    subjects {\n                      apiGroup\n                      kind\n                      name\n                      namespace\n                    }\n                  }\n                }\n              }\n              tokens {\n                name\n                permissions {\n                  rules {\n                    apiGroups\n                    resources\n                    verbs\n                  }\n                }\n                roleRefs {\n                  kind\n                  name\n                  namespace\n                }\n              }\n            }\n          }\n          status {\n            phase\n            access\n            observedGeneration\n            conditions {\n              type\n              status\n              reason\n              message\n              lastTransitionTime\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetMCPsList($workspaceNamespace: String!) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        ManagedControlPlanes(namespace: $workspaceNamespace) {\n          items {\n            metadata {\n              name\n              namespace\n              creationTimestamp\n              annotations\n            }\n            status {\n              status\n              conditions {\n                type\n                status\n                reason\n                message\n                lastTransitionTime\n              }\n              components {\n                authentication {\n                  access {\n                    key\n                    name\n                    namespace\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    core_open_control_plane_io {\n      v2alpha1 {\n        ControlPlanes(namespace: $workspaceNamespace) {\n          items {\n            metadata {\n              name\n              namespace\n              creationTimestamp\n              annotations\n            }\n            status {\n              phase\n              conditions {\n                type\n                status\n                reason\n                message\n                lastTransitionTime\n              }\n              access\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetMCPsList($workspaceNamespace: String!) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        ManagedControlPlanes(namespace: $workspaceNamespace) {\n          items {\n            metadata {\n              name\n              namespace\n              creationTimestamp\n              annotations\n            }\n            status {\n              status\n              conditions {\n                type\n                status\n                reason\n                message\n                lastTransitionTime\n              }\n              components {\n                authentication {\n                  access {\n                    key\n                    name\n                    namespace\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n    core_open_control_plane_io {\n      v2alpha1 {\n        ControlPlanes(namespace: $workspaceNamespace) {\n          items {\n            metadata {\n              name\n              namespace\n              creationTimestamp\n              annotations\n            }\n            status {\n              phase\n              conditions {\n                type\n                status\n                reason\n                message\n                lastTransitionTime\n              }\n              access\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  mutation CreateSelfSubjectRulesReview($object: AuthorizationK8sIoV1SelfSubjectRulesReview_Input!) {\n    authorization_k8s_io {\n      v1 {\n        createSelfSubjectRulesReview(object: $object) {\n          status {\n            evaluationError\n            incomplete\n            resourceRules {\n              apiGroups\n              resources\n              verbs\n              resourceNames\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  mutation CreateSelfSubjectRulesReview($object: AuthorizationK8sIoV1SelfSubjectRulesReview_Input!) {\n    authorization_k8s_io {\n      v1 {\n        createSelfSubjectRulesReview(object: $object) {\n          status {\n            evaluationError\n            incomplete\n            resourceRules {\n              apiGroups\n              resources\n              verbs\n              resourceNames\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetWorkspaces($projectNamespace: String!) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        Workspaces(namespace: $projectNamespace) {\n          items {\n            apiVersion\n            kind\n            metadata {\n              name\n              namespace\n              annotations\n            }\n            spec {\n              members {\n                kind\n                name\n                roles\n                namespace\n              }\n            }\n            status {\n              namespace\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetWorkspaces($projectNamespace: String!) {\n    core_openmcp_cloud {\n      v1alpha1 {\n        Workspaces(namespace: $projectNamespace) {\n          items {\n            apiVersion\n            kind\n            metadata {\n              name\n              namespace\n              annotations\n            }\n            spec {\n              members {\n                kind\n                name\n                roles\n                namespace\n              }\n            }\n            status {\n              namespace\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  subscription WorkspacesSubscription($namespace: String!) {\n    core_openmcp_cloud_v1alpha1_workspaces(namespace: $namespace) {\n      type\n    }\n  }\n',
): (typeof documents)['\n  subscription WorkspacesSubscription($namespace: String!) {\n    core_openmcp_cloud_v1alpha1_workspaces(namespace: $namespace) {\n      type\n    }\n  }\n'];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
