#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

build_plugin() {
  local name="$1"
  local dir="$2"
  local configmap_name="$3"
  local configmap_file="${SCRIPT_DIR}/configmap-${name}-plugin.yaml"

  echo "→ building ${name} plugin..."
  (cd "$dir" && npm run build 2>&1 | tail -3)

  local version
  version=$(node -p "require('${dir}/package.json').version")
  local pkg_json
  pkg_json=$(node -e "
    const p = require('${dir}/package.json');
    console.log(JSON.stringify({name: p.name, version: p.version, devDependencies: p.devDependencies}));
  ")

  {
    echo "# This file is auto-generated by scripts/build-headlamp-plugins.sh — do not edit by hand."
    echo "# Plugin: ${name} v${version}"
    echo "apiVersion: v1"
    echo "kind: ConfigMap"
    echo "metadata:"
    echo "  name: ${configmap_name}"
    echo "  namespace: headlamp"
    echo "data:"
    echo "  package.json: |-"
    echo "    ${pkg_json}"
    echo "  main.js: |-"
    sed 's/^/    /' "${dir}/dist/main.js"
  } > "$configmap_file"

  echo "✓ wrote ${configmap_file}"
}

build_plugin "opencontrolplane" "${ROOT_DIR}/../opencontrolplane-headlamp-plugin" "opencontrolplane-plugin"
