#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CLUSTER_NAME="headlamp-dev"
NAMESPACE="headlamp"
HEADLAMP_VERSION="0.42.0"
PORT=8090

CLUSTER_CREATED=false

kill_port() {
  local port="$1"
  if command -v lsof &>/dev/null; then
    lsof -ti :"$port" | xargs kill -9 2>/dev/null || true
  elif command -v fuser &>/dev/null; then
    fuser -k "${port}/tcp" 2>/dev/null || true
  fi
}

cleanup() {
  echo ""
  echo "✗ Setup failed — cleaning up..."
  kill_port "$PORT"
  if $CLUSTER_CREATED; then
    echo "→ deleting kind cluster '${CLUSTER_NAME}'..."
    kind delete cluster --name "$CLUSTER_NAME" 2>/dev/null || true
  fi
}
trap cleanup ERR

# ── Prerequisites ─────────────────────────────────────────────────────────────
echo "── Checking prerequisites ───────────────────────────────────────────────────"

check_cmd() {
  local cmd="$1"
  local hint="$2"
  if ! command -v "$cmd" &>/dev/null; then
    echo "  ✗ '$cmd' not found — ${hint}" >&2
    return 1
  fi
  echo "  ✓ $cmd ($(command -v "$cmd"))"
}

MISSING=0
check_cmd kind    "install: https://kind.sigs.k8s.io/docs/user/quick-start/#installation"          || MISSING=1
check_cmd kubectl "install: https://kubernetes.io/docs/tasks/tools/"                              || MISSING=1
check_cmd helm    "install: https://helm.sh/docs/intro/install/"                                  || MISSING=1
check_cmd curl    "install via your package manager (brew install curl / apt install curl)"       || MISSING=1
check_cmd node    "install: https://nodejs.org/ or via nvm"                                       || MISSING=1
check_cmd npm     "install: https://nodejs.org/ or via nvm (comes with Node)"                     || MISSING=1
check_cmd python3 "install via your package manager (brew install python3 / apt install python3)" || MISSING=1
check_cmd docker  "install: https://docs.docker.com/get-docker/ (needed by kind)"                || MISSING=1

if [[ $MISSING -ne 0 ]]; then
  echo ""
  echo "error: one or more required tools are missing — install them and re-run." >&2
  exit 1
fi

echo ""

# ── Build plugins from sibling repos ──────────────────────────────────────────
echo "── Building plugins ─────────────────────────────────────────────────────────"

build_plugin() {
  local name="$1"
  local plugin_dir="$2"
  local output_yaml="$3"

  if [[ ! -d "$plugin_dir" ]]; then
    echo "  ✗ ${name} plugin directory not found: ${plugin_dir}" >&2
    echo "    Clone the sibling repo next to this one and re-run." >&2
    return 1
  fi

  echo "→ ${name}: npm install..."
  (cd "$plugin_dir" && npm install --prefer-offline 2>&1 | tail -3)

  echo "→ ${name}: npm run build..."
  local build_log
  if ! build_log=$(cd "$plugin_dir" && npm run build 2>&1); then
    echo ""
    echo "  ✗ ${name} build failed:" >&2
    echo "$build_log" >&2
    return 1
  fi
  echo "$build_log" | grep -E "(dist/|✓|error|warn|kB|ms)" | head -10 || true

  local main_js="${plugin_dir}/dist/main.js"
  if [[ ! -f "$main_js" ]]; then
    echo "  ✗ build did not produce dist/main.js" >&2
    return 1
  fi

  local plugin_name plugin_version
  plugin_name=$(node -e "process.stdout.write(require('${plugin_dir}/package.json').name)")
  plugin_version=$(node -e "process.stdout.write(require('${plugin_dir}/package.json').version)")

  local cm_name
  cm_name="$(echo "${name}" | tr '[:upper:]' '[:lower:]')-plugin"
  echo "→ ${name}: writing ConfigMap ${output_yaml}..."
  python3 - "$output_yaml" "$cm_name" "$plugin_name" "$plugin_version" \
    "${plugin_dir}/package.json" "$main_js" << 'PYEOF'
import sys, pathlib

out_path, cm_name, plugin_name, plugin_version, pkg_path, js_path = sys.argv[1:]
pkg_raw = pathlib.Path(pkg_path).read_text().strip()
js_raw  = pathlib.Path(js_path).read_text().rstrip('\n')

def indent(text):
    return '\n'.join('    ' + line for line in text.splitlines())

yaml = f"""# This file is auto-generated by scripts/setup-headlamp-dev.sh — do not edit by hand.
# Plugin: {plugin_name} v{plugin_version}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {cm_name}
  namespace: headlamp
data:
  package.json: |-
{indent(pkg_raw)}
  main.js: |-
{indent(js_raw)}
"""
pathlib.Path(out_path).write_text(yaml)
PYEOF

  echo "  ✓ ${name} plugin built ($(du -sh "$main_js" | cut -f1) → ${output_yaml##*/})"
}

build_plugin "ocp"        "${SCRIPT_DIR}/../../opencontrolplane-headlamp-plugin" "${SCRIPT_DIR}/configmap-ocp-plugin.yaml"
build_plugin "crossplane" "${SCRIPT_DIR}/../../crossplane-headlamp-plugin" "${SCRIPT_DIR}/configmap-crossplane-plugin.yaml"

echo ""

# ── Kind cluster ──────────────────────────────────────────────────────────────
echo "── Cluster ──────────────────────────────────────────────────────────────────"

if kind get clusters 2>/dev/null | grep -q "^${CLUSTER_NAME}$"; then
  echo "✓ kind cluster '${CLUSTER_NAME}' already exists"
else
  echo "→ creating kind cluster '${CLUSTER_NAME}'..."
  kind create cluster --name "$CLUSTER_NAME"
  CLUSTER_CREATED=true
fi

kubectl config use-context "kind-${CLUSTER_NAME}"

if [[ -f /.dockerenv ]]; then
  echo "→ DooD: joining kind network and patching kubeconfig..."
  docker network connect kind "$(hostname)" 2>/dev/null || true
  CP_IP=$(docker inspect "${CLUSTER_NAME}-control-plane" \
    --format '{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' 2>/dev/null \
    | awk '{print $NF}' | tr -d ' \n' || true)
  [[ -n "$CP_IP" ]] && sed -i "s|server: https://[^'\"]*|server: https://${CP_IP}:6443|g" "$HOME/.kube/config" \
    || echo "  warning: could not determine control-plane IP — kubectl may fail" >&2
fi

echo ""

# ── Namespace + plugin ConfigMaps ─────────────────────────────────────────────
echo "── Deploying ConfigMaps ─────────────────────────────────────────────────────"
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
kubectl apply -f "${SCRIPT_DIR}/configmap-ocp-plugin.yaml"
kubectl apply -f "${SCRIPT_DIR}/configmap-crossplane-plugin.yaml"
echo ""

# ── Headlamp via Helm ─────────────────────────────────────────────────────────
echo "── Deploying Headlamp ${HEADLAMP_VERSION} via Helm ──────────────────────────"
helm repo add headlamp https://kubernetes-sigs.github.io/headlamp/ --force-update &>/dev/null

helm upgrade --install headlamp headlamp/headlamp \
  --version "$HEADLAMP_VERSION" \
  --namespace "$NAMESPACE" \
  --values - \
  --wait --timeout 300s <<'EOF'
replicaCount: 1
config:
  baseURL: /api/headlamp
  pluginsDir: /headlamp/plugins
  extraArgs:
    - -enable-dynamic-clusters
    - -session-ttl=86400
    - -in-cluster-context-name=main
    - -user-plugins-dir=/headlamp/user-plugins
    - -watch-plugins-changes=true
pluginsManager:
  enabled: true
  baseImage: node:lts-alpine@sha256:d1b3b4da11eefd5941e7f0b9cf17783fc99d9c6fc34884a665f40a06dbdfc94f
  configContent: |
    plugins:
      - name: headlamp-flux
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
      - name: headlamp-ocp
        source: https://artifacthub.io/packages/headlamp/opencontrolplane-headlamp-plugin/opencontrolplane
      - name: headlamp-crossplane
        source: https://artifacthub.io/packages/headlamp/crossplane-headlamp-plugin/headlamp_crossplane
EOF

echo ""

# ── Port-forward ──────────────────────────────────────────────────────────────
echo "── Port-forward ─────────────────────────────────────────────────────────────"
if command -v lsof &>/dev/null && lsof -ti :"$PORT" &>/dev/null; then
  echo "→ stopping existing process on port ${PORT}..."
  kill_port "$PORT"
elif command -v fuser &>/dev/null && fuser "${PORT}/tcp" &>/dev/null 2>&1; then
  echo "→ stopping existing process on port ${PORT}..."
  kill_port "$PORT"
fi

echo "→ starting port-forward on http://localhost:${PORT}..."
kubectl port-forward svc/headlamp "$PORT":80 -n "$NAMESPACE" &>/tmp/headlamp-portforward.log &
PF_PID=$!

for i in $(seq 1 20); do
  if curl -s -o /dev/null -w "%{http_code}" "http://localhost:${PORT}/api/headlamp/" | grep -q "200"; then
    break
  fi
  sleep 1
done

echo ""
echo "✓ Headlamp is running at http://localhost:${PORT}/api/headlamp/"
echo "  Port-forward PID: ${PF_PID} (logged to /tmp/headlamp-portforward.log)"
echo "  To stop: kill ${PF_PID}"
echo ""
echo "  Set HEADLAMP_UPSTREAM_URL=http://localhost:${PORT} in your .env, then: npm run dev"
