name: Cleanup main images

on:
  schedule:
    - cron: '5 1 * * *'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Dry run'
        required: false
        default: true
        type: 'boolean'

env:
  REGISTRY: ghcr.io
  ORG: openmcp-project
  IMAGE_NAME: mcp-ui-frontend
  KEEP_X_IMAGES: 5
  TAG_PREFIX: 'main-'

jobs:
  clean:
    name: Clean main images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run == 'true' }}
          packages: ${{ env.IMAGE_NAME }}
          delete-tags: main-*
          delete-untagged: true
          keep-n-tagged: ${{ env.KEEP_X_IMAGES }}
          delete-ghost-images: true
          delete-partial-images: true
