name: On Pull Request
permissions:
  contents: read
  checks: write
  pull-requests: write
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      checks: write
      pull-requests: write
